### ISSUE TITLE
Mapolution failed and aborted

### ISSUE THREAD

**Issue by yogiks** [osmcode/osmium-contrib#4]
I could set up libosmium and successfully build osmium-contrib without errors but while running mapolution with the osmfile, getting this error in the end -

libosmium/include/osmium/osm/node_ref_list.hpp:132: bool osmium::NodeRefList::ends_have_same_location() const: Assertion `front().location() && back().location()' failed.
Aborted

Is there anything to take care before running mapolution.?

Thanks

**Comment by joto** [comment]
Can you tell us which OSM file you have tried this with? Is it an OSM file with full history? Are you sure all nodes needed for the ways are in there?

The error basically says that Osmium is looking at the nodes in the ways and doesn't have a location for them which means they weren't in the file.

**Comment by yogiks** [comment]
Thank you for the response.

Tried it with this file of Nepal - http://osm.personalwerk.de/full-history-extracts/latest/asia/nepal.osh.pbf

How do I know that all nodes needed for the ways are in the above Nepal OSM file.?

**Comment by joto** [comment]
You don't. :-) Basically you have to know how the file was generated.

Often nodes are missing in extracts because they have been cut away during the creation of the extract. This should only affect ways right at the boundary of the extracts and in most cases doesn't matter that much. I have changed Libosmium to ignore this case, pull the newest version of libosmium (not osmium-contrib) and you should be fine.

**Comment by yogiks** [comment]
Awesome!
It worked and this is what I could create with it. :smiley:

![anim](https://cloud.githubusercontent.com/assets/6291913/7273536/488d14d4-e912-11e4-86d4-34885142c2d3.gif)


And is there a way to tell rasterize.sh to include country boundary as background.?

**Comment by joto** [comment]
No. This is a rather simple renderer.

**Comment by yogiks** [comment]
Ok, this is great :+1: 
Thank you :smiley:
