### ISSUE TITLE
pub_names and road_length programs missing?

### ISSUE THREAD

**Issue by garaud** [osmcode/osmium-contrib#7]
Hi,

I read the [osmium-contrib web page](http://osmcode.org/osmium-contrib/) and the links to the **pub_names** and **road_length** directories return a Github 404 error. Is the web page outdated?

Does the code move? or has been removed (and why)?

Thanks,
Damien

**Comment by joto** [comment]
Yes, the web page is outdated (I just fixed it). Those programs have been moved to the [examples](https://github.com/osmcode/libosmium/tree/master/examples) directory in the libosmium repository. They are not really useful as programs, because they are so limited and inflexible, but they are useful as examples, so I thought they better fit in the new place.

**Comment by garaud** [comment]
Ok, it's clear, thanks!
